# Site settings
title: Mystical Notebook
email: zhaojian.dou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Miracles sometimes occur, but one has to work terribly for them. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eddiedou.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  EddieDow

# Build settings
markdown: kramdown
